### PR TITLE
Properly encode all keys and values passed + Base64!

### PR DESCRIPTION
**Pull request by paulstraw**

### CODE REVIEW

**Comment by paulstraw** [comment]
I'm stumped here. I've tried everything I can think of. @cablehead, any ideas?

**Comment by cablehead** [comment]
Pushed up something that's a bit closer. The ~ is just being percent encoded as `self._str_is_ascii(path)` is returning False.

**Comment by cablehead** [comment]
I also pushed up reworking the query string encoding. It was doing `"%s=%s" % (key, val)` which is super ganky. A couple more tests are failing now as they expect `%20` instead of `+`. 

http://stackoverflow.com/questions/1634271/url-encoding-the-space-character-or-20

My encoding foo isn't the strongest. Want to meet up tomorrow to discuss what our ideal encoding should look like?

**Comment by paulstraw** [comment]
Ah, unfortunately `urlencode` doesn't encode everything the way we need it (yeah, it's a bit silly), hence the use of `quote`.

**Comment by paulstraw** [comment]
As far as I'm currently aware, the only difference is the space character encoding, which should be `%20` instead of `+`. Do you think it's jankier to manually replace those characters, or use `quote`?

**Comment by cablehead** [comment]
Ugh apologies, looks like that last push I made is a revert of something that was very intentional: 238d4eca0790f1a4823ae17e6c1f594c2b0cf021 

Guessing there's an issue with using urlencode?

**Comment by paulstraw** [comment]
Yup, no problem. The change I made in 238d4ec could very well be a suboptimal way to handle this. `quote` encodes spaces differently than `urlencode` (more consistent with our other libraries), and seemed like a better option to my non-Pythonic mind. I'm happy to defer to you on the `quote` vs `urlencode` issue, I'm just not sure what the best way to handle the space encoding is in that case.

**Comment by cablehead** [comment]
I'll take a shot at manually replacing spaces with spaces with `+`.

**Comment by paulstraw** [comment]
Also don't feel obligated to keep going on this at all! I just wasn't sure if that was better or worse than using the `quote` method. I'm happy to implement as long as it's got the expert's sign-off! :smile:

**Comment by cablehead** [comment]
Realizing my ganky comment would have come off as harsh. At first I thought that was something you inherited, without realizing you were working around inconsistent behavior in python's `urlencode`. The approach you took totally makes sense. `"%s" % var` just opens up another encoding trap door to juggle between python 2 and 3

**Comment by paulstraw** [comment]
Oh, don't worry about it at all. It's always great to have someone double-checking for bad practices like that when you're not super familiar with all the idioms of a language! :grin: I just appreciate you taking the time to check it out.

**Comment by cablehead** [comment]
Just got the `~` in the path to go. Which I think is an issue with `_str_is_ascii` and Python3

**Comment by cablehead** [comment]
The tests should pass with that last commit. It's just adding to the hodge podge handling of encoding though. Ideally there should be one layer / place that normalizes the encoding of calls to the module, and then the remainder of the module can assume the data is normalized. It's not clear where to put that layer atm with the weird split between builder and helper. Maybe we could chat through a refactor?

**Comment by paulstraw** [comment]
Yeah, definitely would like to chat about a refactor. I'm planning an overhaul of how all of our libraries are structured, with consistent interfaces (as much as idioms allow) across all the languages we support.

**Pull request merged**
