### PR TITLE
feat: customize target Device Pixel Ratios

### PR DESCRIPTION
**Pull request by ashutoshkrris**
## Description

Attempts to fix: #101 

Before this PR, users were not able to customize target DPR and thus the library was generating from 1 to 5 dpr by default.

After this PR, users will be able to pass a `device_pixel_ratios` list in options while creating `srcset` in order to customize the target DPR.

## Steps to test
You can now pass `device_pixel_ratios` as below:
```python
from imgix import UrlBuilder
client = UrlBuilder("demo.imgix.net")
client.create_srcset(
  "image.jpg",
  { "w": 100 },
  {
    "device_pixel_ratios": [ 1, 2, 3 ]
  }
)
```
This will output:
```bash
https://demo.imgix.net/image.jpg?dpr=1&ixlib=python-3.2.1&q=75&w=100 1x,
https://demo.imgix.net/image.jpg?dpr=2&ixlib=python-3.2.1&q=50&w=100 2x,
https://demo.imgix.net/image.jpg?dpr=3&ixlib=python-3.2.1&q=35&w=100 3x'
```
You can also pass `variable_qualities` along with the `device_pixel_ratios` option as below:
```python
from imgix import UrlBuilder
client = UrlBuilder("demo.imgix.net")
client.create_srcset(
  "image.jpg",
  { "w": 100 },
  {
    "device_pixel_ratios": [ 1, 2, 3 ],
    "variable_qualities": { 1: 45, 2: 30, 3: 20 }
  }
)
```
The above script will produce the following output:
```bash
https://testing.imgix.net/image.jpg?dpr=1&q=45&w=100 1x,
https://testing.imgix.net/image.jpg?dpr=2&q=30&w=100 2x,
https://testing.imgix.net/image.jpg?dpr=3&q=20&w=100 3x
```

## Checklist

- [x] Read the [contributing guidelines](CONTRIBUTING.md).
- [x] Each commit follows the [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/#summary) spec format.
- [x] Update the readme (if applicable).
- [ ] Update or add any necessary API documentation (if applicable)
- [x] All existing unit tests are still passing (if applicable).

- [x] Add some [steps](#steps-to-test) so we can test your bug fix or feature (if applicable).
- [x] Add new passing unit tests to cover the code introduced by your PR (if applicable).
- [ ] Any breaking changes are specified on the commit on which they are introduced with `BREAKING CHANGE` in the body of the commit.
- [ ] If this is a big feature with breaking changes, consider opening an issue to discuss first. This is completely up to you, but please keep in mind that your PR might not be accepted.

### CODE REVIEW

**Comment by ashutoshkrris** [comment]
@sherwinski @luqven 
Just a quick suggestion
The **Add PR to project** workflow is failing, probably because its not able to find the github-token. Please add `GH_TOKEN` in the secrets if not added.

**Comment by luqven** [comment]
> @sherwinski @luqven
> Just a quick suggestion
> The **Add PR to project** workflow is failing, probably because its not able to find the github-token. Please add `GH_TOKEN` in the secrets if not added.

Ah, thanks for the heads up. That token was probably rotated and we likely forgot to update the action ENV variable.

**Review by sherwinski — APPROVED** [review]
Looks good @ashutoshkrris, I just added one comment about the documentation

**Comment by sherwinski** [comment]
Thanks for your work here @ashutoshkrris, this is now ready to merge 👍

**Pull request merged**
